### ISSUE TITLE
implicit cast from float to int when using abs

### ISSUE THREAD

**Issue by guibou** [ghorn/dynobud#100]
clang build returns warning here:
https://github.com/ghorn/dynobud/blob/0d8a9494e66b25aa371cf05add923a44688eb173/dynobud-interpolant/cbits/interpolant.cpp#L59

```
external/dynobud/dynobud-interpolant/cbits/interpolant.cpp:59:9: error: using integer absolute value function 'abs' when argument is of floating point type [-Werror,-Wabsolute-value]
    if (abs(ref-v[i])>margin) return false;
        ^
external/dynobud/dynobud-interpolant/cbits/interpolant.cpp:59:9: note: use function 'std::abs' instead
    if (abs(ref-v[i])>margin) return false;
        ^~~
        std::abs
```

I'll be happy to submit a PR, but I don't really understand the semantic and I suspect an incorrect usage of `abs` instead of `std::abs` or `absf`.

**Comment by jaeandersson** [comment]
I think it's supposed to be `fabs`

**Comment by ghorn** [comment]
fixed https://github.com/ghorn/dynobud/commit/78e6f560c40b032fb6b8530c21d089bbc557c23d
